---
version: "3.8"
services:
  minio:
    image: minio/minio:latest
    entrypoint:
      - /entrypoint.sh
    environment:
      MINIO_ROOT_USER: hogehoge
      MINIO_ROOT_PASSWORD: fugafuga
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "./entrypoint.sh:/entrypoint.sh:ro"
      - "./config.json:/mnt/config.json:ro"
      - "./metadata.bin:/mnt/metadata.bin:ro"
  nats:
    image: nats:2.7
    ports:
      - "4222:4222"
  # unzipper:
  #   image: hsmtkk/turbo-doodle:unzipper
  #   environment:
  #     NATS_URL: "nats://nats:4222"
  #     NATS_SUBJECT: test
  #     MINIO_HOST: minio
  #     MINIO_PORT: 9000
  #     MINIO_ROOT_USER: hogehoge
  #     MINIO_ROOT_PASSWORD: fugafuga
