---
apiVersion: v1
kind: Pod
metadata:
  name: minio
spec:
  containers:
    - name: minio
      image: minio/minio:latest
      args:
        - server
        - /data
        - --console-address
        - ":9001"
      env:
        - name: MINIO_ROOT_USER
          value: minioadmin
        - name: MINIO_ROOT_PASSWORD
          value: minioadmin
      ports:
        - name: web
          protocol: TCP
          containerPort: 9000
          hostPort: 9000
        - name: console
          protocol: TCP
          containerPort: 9001
          hostPort: 9001
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: data
