---
apiVersion: v1
kind: Pod
metadata:
  name: turbo-doodle
spec:
  containers:
    - name: busybox
      image: busybox:1.34
      command:
        - mkdir
        - /data/default-bucket
      volumeMounts:
        - name: data
          mountPath: /data
    - name: minio
      image: minio/minio:latest
      args:
        - server
        - /data
        - --console-address
        - ":9001"
      env:
        - name: MINIO_ROOT_USER
          value: hogehoge
        - name: MINIO_ROOT_PASSWORD
          value: fugafuga
        - name: MINIO_NOTIFY_NATS_ENABLE
          value: "on"
        - name: MINIO_NOTIFY_NATS_ADDRESS
          value: "127.0.0.1"
        - name: MINIO_NOTIFY_NATS_SUBJECT
          value: "default-subject"
      ports:
        - name: web
          protocol: TCP
          containerPort: 9000
          hostPort: 9000
        - name: console
          protocol: TCP
          containerPort: 9001
          hostPort: 9001
      volumeMounts:
        - name: data
          mountPath: /data
    - name: nats
      image: nats:2.7
      ports:
        - name: nats
          protocol: TCP
          containerPort: 4222
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: data
